# Generated by Django 5.1.6 on 2025-02-21 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.CharField(max_length=5000)),
                ('categoria', models.CharField(max_length=80)),
                ('immagine', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Preferito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
            ],
        ),
    ]
