# Generated by Django 5.1.7 on 2025-03-23 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='anno_uscita',
            field=models.CharField(default=2000, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='artista',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='etichetta',
            field=models.CharField(default=2000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prodotto',
            name='link_streaming',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=5000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
                ('id_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valutazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id_prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodotti.prodotto')),
                ('id_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
