# Generated by Django 5.1.7 on 2025-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0002_prodotto_anno_uscita_prodotto_artista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='lingua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nazione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
