# Generated by Django 5.1.6 on 2025-05-08 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0003_prodotto_lingua_prodotto_nazione'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='preferiti',
            field=models.ManyToManyField(blank=True, related_name='prodotti_prefriti', to=settings.AUTH_USER_MODEL),
        ),
    ]
